services:
  wordpress:
    build:
      context: ./.docker
      args:
        WP_VERSION: ${WP_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    image: ${PLUGIN_SLUG}:latest-wp${WP_VERSION}-php${PHP_VERSION}
    restart: always
    ports:
      - "8890:80"
    environment:
      WP_VERSION: ${WP_VERSION}
      PHP_VERSION: ${PHP_VERSION}
      COVERAGE: ${COVERAGE:-}
    env_file:
      - .env
    user: root
    depends_on:
      - mysql
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/${PLUGIN_SLUG}
    networks:
      - plugin_network

  mysql:
    image: mariadb:10
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
    volumes:
      - db:/var/lib/mysql
    networks:
      - plugin_network

networks:
  plugin_network:
    driver: bridge

volumes:
  wordpress_data:
  db:
