const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
const path = require( 'path' );
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const TsconfigPathsPlugin = require( 'tsconfig-paths-webpack-plugin' );

// Extend the default webpack config.
const mainConfig = {
	...defaultConfig,
	// context: path.resolve(__dirname, 'src', 'assets'),
	module: {
		...defaultConfig.module,
		rules: [
			...defaultConfig.module.rules,
			{
				test: /\.svg$/,
				use: [ '@svgr/webpack', 'url-loader' ],
			},
		],
	},
	entry: {
		admin: path.resolve( process.cwd(), 'packages/admin', 'index.tsx' ),
	},
	resolve: {
		...defaultConfig.resolve,
		plugins: [
			...( defaultConfig.resolve.plugins || [] ),
			new TsconfigPathsPlugin( { configFile: './tsconfig.json' } ),
		],
	},

	output: {
		...defaultConfig.output,
		clean: false, // Don't clean for multi-config setup
	},

	plugins: [
		...defaultConfig.plugins.filter(
			( plugin ) => plugin.constructor.name !== 'CleanWebpackPlugin'
		),

		// Removes the empty `.js` files generated by webpack after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};

const reactJSXRuntimePolyfill = {
	entry: {
		'react-jsx-runtime': {
			import: 'react/jsx-runtime',
		},
	},
	output: {
		path: path.resolve( __dirname, 'build' ),
		filename: 'react-jsx-runtime.js',
		library: {
			name: 'ReactJSXRuntime',
			type: 'window',
		},
	},
	externals: {
		react: 'React',
	},
	plugins: [],
};

module.exports = [ mainConfig, reactJSXRuntimePolyfill ];
