name: JS Tests + Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - 'bin/**'
      - '.github/workflows/js-tests.yml'
      - 'build/**'
      - 'packages/**'
      - '**/*.{ts,tsx,js,jsx}'
      - 'vitest.config.ts'
      - 'vitest.setup.ts'
      - 'tsconfig.json'
      - 'tsconfig.base.json'
      - 'package.json'
      - 'package-lock.json'

concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Vitest with Coverage
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Vitest with coverage
        run: npm run test:js:coverage

      - name: Upload HTML coverage report as artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: vitest-coverage-report
          path: ./tests/_output/coverage/html
          overwrite: true

      - name: Upload code coverage report
        continue-on-error: true
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/_output/coverage/lcov.info, ./tests/_output/coverage/coverage-final.json
          flags: javascript
          name: codecov-js
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
