name: JS Tests + Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - 'bin/**'
      - '.github/workflows/js-tests.yml'
      - 'build/**'
      - 'packages/**'
      - '**/*.{ts,tsx,js,jsx}'
      - 'vitest.config.ts'
      - 'vitest.setup.ts'
      - 'tsconfig.json'
      - 'tsconfig.base.json'
      - 'package.json'
      - 'package-lock.json'

concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    uses: AxeWP/plugin-infra/.github/workflows/reusable-jest.yml@main
    with:
      coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
