name: JS/CSS Linting

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - 'bin/**'
      - '.github/workflows/package-linter.yml'
      - 'build/**'
      - 'packages/**'
      - '**/*.{ts,tsx,js,jsx}'
      - '.eslintignore'
      - '.prettierignore'
      - '.stylelintrc.json'
      - 'global.d.ts'
      - 'package-lock.json'
      - 'package.json'
      - 'tsconfig.base.json'
      - 'tsconfig.json'

# Cancel previous workflow run groups that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    uses: AxeWP/plugin-infra/.github/workflows/reusable-lint-js.yml@main

  build:
    name: Check Assets build
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install NPM dependencies
        run: npm ci

      - name: Check Assets build
        run: npm run build:js
