name: JS/CSS Linting

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - 'bin/**'
      - '.github/workflows/package-linter.yml'
      - '**.js'
      - 'build/**'
      - 'packages/**'
      - '.eslintignore'
      - '.prettierignore'
      - '.stylelintrc.json'
      - 'global.d.ts'
      - 'package-lock.json'
      - 'package.json'
      - 'tsconfig.base.json'
      - 'tsconfig.json'

# Cancel previous workflow run groups that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  run:
    name: Check packages
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2.35.4
        with:
          php-version: 8.4
          coverage: none
          tools: cs2pr

      # This date is used to ensure that the PHPCS cache is cleared at least once every week.
      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: "Get last Monday's date"
        id: get-date
        run: echo "date=$(/bin/date -u --date='last Mon' "+%F")" >> "$GITHUB_OUTPUT"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # v3.1.1

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> "$GITHUB_PATH"

      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install NPM dependencies
        run: npm ci

      - name: Lint JS
        run: npm run lint:js

      - name: Lint CSS
        run: npm run lint:css

      - name: Lint TypeScript
        run: npm run ts:check

      - name: Check Assets build
        run: npm run build:prod
