name: PHPCS

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - 'src/**'
      - '.github/workflows/phpcs.yml'
      - '**.php'
      - '.phpcs.xml.dist'
      - 'composer.json'
      - 'composer.lock'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  phpcs:
    uses: AxeWP/plugin-infra/.github/workflows/reusable-phpcs.yml@main
    with:
      php-version: '8.4'
