name: PHP Static Analysis

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '.github/workflows/phpstan.yml'
      - '**.php'
      - 'bin/**'
      - '.env.dist'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon.dist'

# Cancel previous workflow run groups that have not completed.
concurrency:
  # Group workflow runs by workflow name, along with the head branch ref of the pull request
  # or otherwise the branch or tag ref.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code with PHPStan

    services:
      mysql:
        image: mariadb:10
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        # Ensure docker waits for mariadb to start
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP w/ Composer & WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          coverage: none
          tools: composer:v2, wp-cli

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-progress"

      - name: Setup WordPress
        run: |
          cp .env.dist .env
          composer run install-test-env
          # Remove the symlinked plugin and copy the plugin to the WordPress install
          rm -rf /tmp/wordpress/wp-content/plugins/wp-graphql-headless-login
          cp -R . /tmp/wordpress/wp-content/plugins/wp-graphql-headless-login

      - name: Run PHPStan
        working-directory: /tmp/wordpress/wp-content/plugins/wp-graphql-headless-login
        run: composer run-script phpstan -- --error-format=github
