name: Spelling

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

# Cancel previous workflow run groups that have not completed.
concurrency:
  # Group workflow runs by workflow name, along with the head branch ref of the pull request
  # or otherwise the branch or tag ref.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  typos:
    runs-on: ubuntu-latest
    name: Typos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Typos
        uses: crate-ci/typos@master
