name: Upload Release Package

on:
  release:
    types: [ published ]

jobs:
  tag:
    name: Upload New Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          extensions: mbstring, intl
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-progress"

      - name: Install Node.js dependencies
        run: npm ci
        env:
          CI: true

      - name: Build assets
        run: |
          composer install --no-dev --optimize-autoloader
          npm run build

      - name: Create Artifact
        run: |
          mkdir plugin-build
          composer archive -vvv --format=zip --file="plugin-build/wp-graphql-headless-login"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wp-graphql-headless-login
          path: plugin-build/wp-graphql-headless-login.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: plugin-build/wp-graphql-headless-login.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
